CREATE TABLE "User" (
  "User_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Username" varchar,
  "Email" varchar,
  "Password" varchar,
  "Role" varchar,
  "Created_At" datetime
);

CREATE TABLE "CourseCategory" (
  "Category_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar,
  "Description" text
);

CREATE TABLE "Course" (
  "Course_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar,
  "Description" varchar,
  "Category_ID" int,
  "Created_By" int,
  "Created_At" datetime
);

CREATE TABLE "Lesson" (
  "Lesson_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar,
  "Content" text,
  "Course_ID" int
);

CREATE TABLE "Enrollment" (
  "Enrollment_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" int,
  "Course_ID" int,
  "Enrolled_At" datetime
);

CREATE TABLE "Progress" (
  "Progress_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" int,
  "Course_ID" int,
  "Lesson_ID" int,
  "Completion_Percentage" float,
  "Updated_At" datetime
);

CREATE TABLE "Payment" (
  "Payment_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" int,
  "Amount" decimal,
  "Payment_Date" datetime
);

CREATE TABLE "Review" (
  "Review_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" int,
  "Course_ID" int,
  "Rating" int,
  "Comment" text,
  "Created_At" datetime
);

CREATE TABLE "Notification" (
  "Notification_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" int,
  "Message" text,
  "Sent_At" datetime,
  "Read_At" datetime
);

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Enrollment" ("User_ID");

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Progress" ("User_ID");

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Payment" ("User_ID");

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Review" ("User_ID");

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Notification" ("User_ID");

ALTER TABLE "CourseCategory" ADD FOREIGN KEY ("Category_ID") REFERENCES "Course" ("Category_ID");

ALTER TABLE "User" ADD FOREIGN KEY ("User_ID") REFERENCES "Course" ("Created_By");

ALTER TABLE "Course" ADD FOREIGN KEY ("Course_ID") REFERENCES "Lesson" ("Course_ID");

ALTER TABLE "Course" ADD FOREIGN KEY ("Course_ID") REFERENCES "Enrollment" ("Course_ID");

ALTER TABLE "Course" ADD FOREIGN KEY ("Course_ID") REFERENCES "Progress" ("Course_ID");

ALTER TABLE "Course" ADD FOREIGN KEY ("Course_ID") REFERENCES "Review" ("Course_ID");

ALTER TABLE "Lesson" ADD FOREIGN KEY ("Lesson_ID") REFERENCES "Progress" ("Lesson_ID");
